import random , os , time
os.system ("clear")
######################################
print("              CLAY.CLAY.CLAY.CLAY ")
print("              ___________________")
print("             /                   \ ")
print("            /    __           __  \ ")
print("           /    /^^\         /^^\  \ ")
print("          /     \__/         \__/   \ ")
print("         /                           \  ")
print("        /                             \ ")
print("       /                __             \ ")
print("      /       ____     /  |  \   /      \ ")
print("     |       |     |    __|   \ /        | ")
print("     |       |____ |   |__|    /         | ")
print("     |                        /          | ")
print("      \               @@@@@@            / ")
print("       \        ..... hacker ......    / ")            
print("        \             @@@@@@          / ")
print("         \___________________________/  ")                            
print("               |                 | ")
#################################################
print("made by clay88")
time.sleep(2)
print("")
print("this tool made to gusse a google play cards")
print("")
time.sleep(4)
print("please wait...")
time.sleep(7)
print("")
letter = ["A" , "B" , "C" , "D" , "E" , "F" , "G" , "H" , "I" , "J" , "K" , "L" , "M" , "N" , "O" , "P" , "Q" , "R" , "S" , "T" , "V" , "W" , "X" , "Y" , "Z"]
numbers = [ 1 , 2 , 3 , 4 , 5 , 7 , 6 , 8 , 9 ]
####random letter code
randomletter1=random.choice(letter)
randomletter2=random.choice(letter)
randomletter3=random.choice(letter)
randomletter4=random.choice(letter)
randomletter5=random.choice(letter)
randomletter6=random.choice(letter)
randomletter7=random.choice(letter)
randomletter8=random.choice(letter)
randomletter9=random.choice(letter)
randomletter10=random.choice(letter)
randomletter11=random.choice(letter)
randomletter12=random.choice(letter)
randomletter13=random.choice(letter)
randomletter14=random.choice(letter)
####random numbers code
randomnumber1=random.choice(numbers)
randomnumber2=random.choice(numbers)
randomnumber3=random.choice(numbers)
randomnumber4=random.choice(numbers)
randomnumber5=random.choice(numbers)
randomnumber6=random.choice(numbers)
####################################
yes = ["y" , "Y" , "yes" , "Yes"]
complet = ("")
####################################
retry="yes"
while retry == "yes" :
    while complet not in yes :
        complet = input ("to countinue writ[y,yes]? ")
        if complet == "Y" or complet == "Yes" or complet == "yes" or complet == "y" :
            os.system("clear")
            print("[1] "+randomletter1+randomletter2+randomletter3+randomletter4+"-"+randomletter5+randomletter6+randomletter7+randomletter8+"-"+randomletter9+str (randomnumber1)+randomletter10+str (randomnumber2)+"-"+randomletter11+randomletter12+randomletter13+str (randomnumber3)+"-"+str (randomnumber4)+str(randomnumber5)+randomletter14+str(randomnumber6))
            time.sleep(0.3)      
            print("[2] "+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+str (random.choice(numbers))+random.choice(letter)+str (random.choice(numbers))+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+str (random.choice(numbers))+"-"+str (random.choice(numbers))+str (random.choice(numbers))+random.choice(letter)+str(random.choice(numbers)))
            time.sleep(0.3)
            print("[3] "+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+str (random.choice(numbers))+random.choice(letter)+str (random.choice(numbers))+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+str (random.choice(numbers))+"-"+str (random.choice(numbers))+str (random.choice(numbers))+random.choice(letter)+str(random.choice(numbers))) 
            time.sleep(0.3)
            print("[4] "+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+str (random.choice(numbers))+random.choice(letter)+str (random.choice(numbers))+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+str (random.choice(numbers))+"-"+str (random.choice(numbers))+str (random.choice(numbers))+random.choice(letter)+str(random.choice(numbers)))
            time.sleep(0.3)
            print("[5] "+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+str (random.choice(numbers))+random.choice(letter)+str (random.choice(numbers))+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+str (random.choice(numbers))+"-"+str (random.choice(numbers))+str (random.choice(numbers))+random.choice(letter)+str(random.choice(numbers)))
            time.sleep(0.3)
            print("[6] "+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+str (random.choice(numbers))+random.choice(letter)+str (random.choice(numbers))+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+str (random.choice(numbers))+"-"+str (random.choice(numbers))+str (random.choice(numbers))+random.choice(letter)+str(random.choice(numbers)))
            time.sleep(0.3)
            print("[7] "+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+str (random.choice(numbers))+random.choice(letter)+str (random.choice(numbers))+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+str (random.choice(numbers))+"-"+str (random.choice(numbers))+str (random.choice(numbers))+random.choice(letter)+str(random.choice(numbers)))
            time.sleep(0.3)
            print("[8] "+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+str (random.choice(numbers))+random.choice(letter)+str (random.choice(numbers))+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+str (random.choice(numbers))+"-"+str (random.choice(numbers))+str (random.choice(numbers))+random.choice(letter)+str(random.choice(numbers)))     
            time.sleep(0.3)
            print("[9] "+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+str (random.choice(numbers))+random.choice(letter)+str (random.choice(numbers))+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+str (random.choice(numbers))+"-"+str (random.choice(numbers))+str (random.choice(numbers))+random.choice(letter)+str(random.choice(numbers)))
            time.sleep(0.3)
            print("[10] "+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+str (random.choice(numbers))+random.choice(letter)+str (random.choice(numbers))+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+str (random.choice(numbers))+"-"+str (random.choice(numbers))+str (random.choice(numbers))+random.choice(letter)+str(random.choice(numbers)))
            time.sleep(0.3)
            print("[11] "+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+str (random.choice(numbers))+random.choice(letter)+str (random.choice(numbers))+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+str (random.choice(numbers))+"-"+str (random.choice(numbers))+str (random.choice(numbers))+random.choice(letter)+str(random.choice(numbers)))
            time.sleep(0.3)
            print("[12] "+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+str (random.choice(numbers))+random.choice(letter)+str (random.choice(numbers))+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+str (random.choice(numbers))+"-"+str (random.choice(numbers))+str (random.choice(numbers))+random.choice(letter)+str(random.choice(numbers)))
            time.sleep(0.3)
            print("[13] "+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+str (random.choice(numbers))+random.choice(letter)+str (random.choice(numbers))+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+str (random.choice(numbers))+"-"+str (random.choice(numbers))+str (random.choice(numbers))+random.choice(letter)+str(random.choice(numbers)))
            time.sleep(0.3)
            print("[14] "+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+str (random.choice(numbers))+random.choice(letter)+str (random.choice(numbers))+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+str (random.choice(numbers))+"-"+str (random.choice(numbers))+str (random.choice(numbers))+random.choice(letter)+str(random.choice(numbers)))
            time.sleep(0.3)
            print("[15] "+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+str (random.choice(numbers))+random.choice(letter)+str (random.choice(numbers))+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+str (random.choice(numbers))+"-"+str (random.choice(numbers))+str (random.choice(numbers))+random.choice(letter)+str(random.choice(numbers)))
            time.sleep(0.3)
            print("[16] "+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+str (random.choice(numbers))+random.choice(letter)+str (random.choice(numbers))+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+str (random.choice(numbers))+"-"+str (random.choice(numbers))+str (random.choice(numbers))+random.choice(letter)+str(random.choice(numbers)))
            time.sleep(0.3)
            print("[17] "+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+str (random.choice(numbers))+random.choice(letter)+str (random.choice(numbers))+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+str (random.choice(numbers))+"-"+str (random.choice(numbers))+str (random.choice(numbers))+random.choice(letter)+str(random.choice(numbers)))
            time.sleep(0.3)
            print("[18] "+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+str (random.choice(numbers))+random.choice(letter)+str (random.choice(numbers))+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+str (random.choice(numbers))+"-"+str (random.choice(numbers))+str (random.choice(numbers))+random.choice(letter)+str(random.choice(numbers)))
            time.sleep(0.3)
            print("[19] "+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+str (random.choice(numbers))+random.choice(letter)+str (random.choice(numbers))+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+str (random.choice(numbers))+"-"+str (random.choice(numbers))+str (random.choice(numbers))+random.choice(letter)+str(random.choice(numbers)))
            time.sleep(0.3)
            print("[20] "+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+random.choice(letter)+"-"+random.choice(letter)+str (random.choice(numbers))+random.choice(letter)+str (random.choice(numbers))+"-"+random.choice(letter)+random.choice(letter)+random.choice(letter)+str (random.choice(numbers))+"-"+str (random.choice(numbers))+str (random.choice(numbers))+random.choice(letter)+str(random.choice(numbers)))
        else:
            complet = ""
retry = input ("to countinue writ [yes] or [no]? ")

